name: Cache Flutter By Version
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Flutter Version'
        required: true
        default: '2.5.1'

jobs:
  install_flutter_cache:
    name: Install & Cache Flutter on  ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - name: Cache Flutter dependencies
        id: cache-flutter
        uses: actions/cache@v2.1.6
        with:
          path: ${{ github.workspace }}/flutter
          key: ${{ runner.OS }}-flutter-install-cache-${{ github.event.inputs.version }}

      - name: Prepare Flutter
        if: steps.cache-flutter.outputs.cache-hit != 'true'
        run: |
            cd ${{ github.workspace }}
            git clone --depth 1 --branch ${{ github.event.inputs.version }} https://github.com/flutter/flutter.git
      - name: Export Flutter path
        run: |
            echo "${{ github.workspace }}/flutter/bin" >> $GITHUB_PATH
            echo "${{ github.workspace }}/flutter/bin/cache/dart-sdk/bin" >> $GITHUB_PATH
      - name: Install Flutter Tools
        run: |
            flutter config --no-analytics
            flutter precache
